# Node reloads this file on change (mtime cache). Bake only for browser/publish: yarn compile:layout

# lv = level
# ms = message
# mt = meta
# id = identity
# ev = event
# mj = emoji
# title = title
# subtitle = subtitle
# md = module
# version = version

text:
  default: |
    [%lv%  ]  [----%md%----] [%ms% ----------------------] [%mt%]

  complex: |
    [%lv%  ]  [%mj%][%ms% -----------------------------][----%md%----]
    [------]  [----][%mt%]

event:
  default: |
    [%mj%] [%ev% -----------------------] [%mt%]

  complex: |
    [%id% -------------------]  [%mj%][%ev% -----------------------]
    [%id% -------------------]  [----][%mt%]

box:
  default: |
    [------------------------------------------------]
    [------------------- %title% --------------------]
    [------------------------------------------------]

  complex: |
    [------------------------------------------------]
    [-------- %title% %version% - %lv% level --------]
    [------------------------------------------------]
    [------------------------------------------------]
    [------------------ %subtitle% ------------------]
    [------------------------------------------------]

tint:
  multiplier: 31
