# yarn build → src/layout/layout.data.ts

# lv = level
# ms = message
# mt = meta
# id = identity
# ev = event
# mj = emoji
# title = title
# subtitle = subtitle
# md = module
# version = version

text:
  default: |
    [%lv%  ]  [%mj%][%ms% -----------------------------][------------- %md%]
    [------]  [----][%mt%]

  complex: |
    [%mj%][%ms% -------------------------------------------------][----------- %md%]
    [----][%mt%]

  # Identity chip + emoji + message + module (no level)
  identity: |
    [%id% -------------------]  [%mj%][%ms% -------------------------------------------------][----------- %md%]
    [------------------------]  [----][%mt%]

event:
  default: |
    [ ---------- %id% ---------- ]  [%mj%][%ev% -----------------------]
    [----------------------------]  [----][%mt%]

  complex: |
    [%id% -------------------]  [%mj%][%ev% -----------------------]
    [%id% -------------------]  [----][%mt%]

box:
  default: |
    [------------------------------------------------]
    [------------------- %title% --------------------]
    [------------------------------------------------]

  complex: |
    [------------------------------------------------]
    [-------- %title% %version% - %lv% level --------]
    [------------------------------------------------]
    [------------------ %subtitle% ------------------]
    [------------------------------------------------]

tint:
  multiplier: 31
